CREATE DATABASE WWE_SHOP_DB;

USE WWE_SHOP_DB;

CREATE TABLE ADDRESS (
    ADDRESS_ID INT IDENTITY(1,1) PRIMARY KEY,
    STREET VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    COUNTRY VARCHAR(50) NOT NULL
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(15),
    ADDRESS_ID INT FOREIGN KEY REFERENCES ADDRESS(ADDRESS_ID),
    CREATED_AT DATETIME DEFAULT GETDATE()
);

CREATE TABLE CATEGORY (
    CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION TEXT
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL,
    CATEGORY_ID INT NOT NULL FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID),
    CREATED_AT DATETIME DEFAULT GETDATE()
);

CREATE TABLE ORDER_HEADER (
    ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    ORDER_DATE DATETIME DEFAULT GETDATE(),
    STATUS VARCHAR(20) CHECK (STATUS IN ('Pending', 'Shipped', 'Delivered', 'Canceled')),
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL
);

CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES ORDER_HEADER(ORDER_ID),
    PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE AS (QUANTITY * UNIT_PRICE) PERSISTED
);

CREATE TABLE PAYMENT (
    PAYMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES ORDER_HEADER(ORDER_ID),
    PAYMENT_DATE DATETIME DEFAULT GETDATE(),
    PAYMENT_METHOD VARCHAR(20) CHECK (PAYMENT_METHOD IN ('Credit Card', 'PayPal', 'Bank Transfer')),
    AMOUNT DECIMAL(10,2) NOT NULL
);

CREATE TABLE PRODUCT_REVIEW (
    REVIEW_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
    CUSTOMER_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    RATING INT CHECK (RATING BETWEEN 1 AND 5),
    REVIEW_TEXT TEXT,
    REVIEW_DATE DATETIME DEFAULT GETDATE()
);
